import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  try {
    const { listing, outputs, type } = await request.json()

    if (type === 'mls') {
      const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Georgia, serif; color: #111; background: #fff; }
    .page { max-width: 800px; margin: 0 auto; padding: 40px; }
    .header { border-bottom: 3px solid #1D9E75; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
    .brand { font-size: 22px; font-weight: bold; color: #1D9E75; font-family: Arial, sans-serif; }
    .property-title { font-size: 28px; font-weight: bold; margin-bottom: 8px; }
    .property-details { font-size: 14px; color: #555; margin-bottom: 4px; }
    .price { font-size: 24px; font-weight: bold; color: #1D9E75; }
    .section { margin-bottom: 28px; }
    .section-title { font-size: 13px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; color: #1D9E75; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 6px; }
    .body-text { font-size: 14px; line-height: 1.8; color: #333; }
    .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div>
        <div class="brand">ListingWhisperer</div>
        <div style="font-size:12px;color:#999;margin-top:4px;">AI-Generated Marketing Copy</div>
      </div>
      <div style="text-align:right">
        <div class="price">${listing.price || ''}</div>
        <div style="font-size:13px;color:#555;">${listing.neighborhood || ''}</div>
      </div>
    </div>

    <div style="margin-bottom:24px;">
      <div class="property-title">${listing.type || 'Property'} — ${listing.beds || ''}</div>
      <div class="property-details">${listing.sqft || ''} sq ft &nbsp;|&nbsp; ${listing.neighborhood || ''}</div>
    </div>

    <div class="section">
      <div class="section-title">MLS Description</div>
      <div class="body-text">${outputs.mls_standard || ''}</div>
    </div>

    <div class="section">
      <div class="section-title">Luxury MLS Version</div>
      <div class="body-text">${outputs.mls_luxury || ''}</div>
    </div>

    <div class="two-col">
      <div class="section">
        <div class="section-title">Instagram Caption</div>
        <div class="body-text" style="white-space:pre-wrap;">${(outputs.instagram || '').split('---')[0].trim()}</div>
      </div>
      <div class="section">
        <div class="section-title">Open House</div>
        <div class="body-text">${outputs.openhouse || ''}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Email Blast</div>
      <div class="body-text" style="white-space:pre-wrap;">${outputs.email || ''}</div>
    </div>

    <div class="footer">
      Generated by ListingWhisperer.com &nbsp;|&nbsp; AI Marketing Copy for Real Estate Agents
    </div>
  </div>
</body>
</html>`

      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
        }
      })
    }

    if (type === 'flyer') {
      const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Arial, sans-serif; color: #111; background: #fff; }
    .page { max-width: 600px; margin: 0 auto; padding: 40px; }
    .header { background: #1D9E75; color: #fff; padding: 30px; text-align: center; border-radius: 12px; margin-bottom: 24px; }
    .brand { font-size: 12px; letter-spacing: 2px; text-transform: uppercase; opacity: 0.8; margin-bottom: 8px; }
    .price { font-size: 36px; font-weight: bold; margin-bottom: 4px; }
    .address { font-size: 16px; opacity: 0.9; }
    .details-bar { display: flex; justify-content: center; gap: 24px; background: #f0fdf8; border: 1px solid #bbf0d9; border-radius: 8px; padding: 16px; margin-bottom: 24px; }
    .detail { text-align: center; }
    .detail-value { font-size: 20px; font-weight: bold; color: #1D9E75; }
    .detail-label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; color: #1D9E75; margin-bottom: 8px; }
    .body-text { font-size: 13px; line-height: 1.8; color: #333; }
    .features { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
    .feature { font-size: 13px; color: #333; padding: 6px 10px; background: #f9f9f9; border-radius: 6px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 2px solid #1D9E75; display: flex; justify-content: space-between; align-items: center; }
    .agent-info { font-size: 13px; color: #333; }
    .watermark { font-size: 11px; color: #999; }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div class="brand">Just Listed</div>
      <div class="price">${listing.price || ''}</div>
      <div class="address">${listing.neighborhood || ''}</div>
    </div>

    <div class="details-bar">
      <div class="detail">
        <div class="detail-value">${(listing.beds || '').split('/')[0].trim()}</div>
        <div class="detail-label">Beds</div>
      </div>
      <div class="detail">
        <div class="detail-value">${(listing.beds || '').split('/')[1]?.trim() || ''}</div>
        <div class="detail-label">Baths</div>
      </div>
      <div class="detail">
        <div class="detail-value">${listing.sqft || ''}</div>
        <div class="detail-label">Sq Ft</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">About This Home</div>
      <div class="body-text">${outputs.mls_standard || ''}</div>
    </div>

    <div class="section">
      <div class="section-title">Key Features</div>
      <div class="features">
        ${(listing.features || '').split(',').map((f: string) => `<div class="feature">✓ ${f.trim()}</div>`).join('')}
      </div>
    </div>

    <div class="section">
      <div class="section-title">Open House</div>
      <div class="body-text">${outputs.openhouse || ''}</div>
    </div>

    <div class="footer">
      <div class="agent-info">
        <strong>Listed by Listing Whisperer Agent</strong><br/>
        Contact for private showing
      </div>
      <div class="watermark">Generated by ListingWhisperer.com</div>
    </div>
  </div>
</body>
</html>`

      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
        }
      })
    }

    return NextResponse.json({ error: 'Invalid type' }, { status: 400 })

  } catch(e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}