import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body className="min-h-full flex flex-col">
  <nav className="w-full bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between">
    <a href="/" className="text-green-600 font-bold text-lg">Listing Whisperer</a>
    <div className="flex gap-4 items-center">
      <a href="/dashboard" className="text-gray-600 hover:text-gray-900 text-sm">Dashboard</a>
      <a href="/pricing" className="bg-green-600 text-white text-sm px-4 py-2 rounded-lg hover:bg-green-700">Upgrade</a>
    </div>
  </nav>
  {children}
</body>
    </html>
  );
}
