import jsPDF from 'jspdf'

export const PDF_COLORS = {
  brand: '#1D9E75',
  brandDark: '#085041',
  dark: '#0d1117',
  text: '#1e1e2e',
  textMid: '#4a4f62',
  textLight: '#8b8fa8',
  white: '#ffffff',
  lightGray: '#f5f7fa',
  border: '#e5e7eb',
  gold: '#d4af37',
}

export const PDF_FONTS = {
  title: { size: 22, weight: 'bold' },
  sectionHeader: { size: 13, weight: 'bold' },
  subheading: { size: 11, weight: 'bold' },
  body: { size: 10, weight: 'normal' },
  caption: { size: 9, weight: 'normal' },
  footer: { size: 7, weight: 'normal' },
}

export const PDF_SPACING = {
  pageMargin: 18,
  sectionGap: 14,
  lineHeight: 5.5,
  paragraphGap: 8,
}

function h(color: string): [number, number, number] {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(color)!
  return [parseInt(r[1], 16), parseInt(r[2], 16), parseInt(r[3], 16)]
}

export function pdfHeader(doc: jsPDF, docType: string, rightLabel: string): number {
  const W = doc.internal.pageSize.getWidth()
  const m = PDF_SPACING.pageMargin

  doc.setFillColor(...h(PDF_COLORS.dark))
  doc.rect(0, 0, W, 40, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...h(PDF_COLORS.white))
  doc.text('Listing', m, 17)
  doc.setTextColor(...h(PDF_COLORS.brand))
  doc.text('Whisperer', m + doc.getTextWidth('Listing') + 1.5, 17)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...h(PDF_COLORS.textLight))
  doc.text(docType.toUpperCase(), W / 2, 17, { align: 'center' })

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...h(PDF_COLORS.textLight))
  if (rightLabel) doc.text(rightLabel, W - m, 17, { align: 'right' })

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
  doc.setFontSize(7.5)
  doc.text(dateStr, W - m, 28, { align: 'right' })

  doc.setFillColor(...h(PDF_COLORS.brand))
  doc.rect(0, 40, W, 2, 'F')

  return 50
}

export function pdfFooter(doc: jsPDF): void {
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  doc.setFillColor(...h(PDF_COLORS.dark))
  doc.rect(0, H - 12, W, 12, 'F')
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...h(PDF_COLORS.textLight))
  doc.text('Generated by ListingWhisperer.com — AI Assistant for Real Estate Agents', W / 2, H - 4.5, { align: 'center' })
}

export function pdfAgentBar(
  doc: jsPDF,
  bv: { agentName?: string; brokerage?: string; phone?: string } | null | undefined,
  y: number
): number {
  if (!bv?.agentName && !bv?.phone) return y
  const W = doc.internal.pageSize.getWidth()
  const m = PDF_SPACING.pageMargin
  const cW = W - m * 2
  doc.setFillColor(...h(PDF_COLORS.lightGray))
  doc.roundedRect(m, y, cW, 15, 2, 2, 'F')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...h(PDF_COLORS.text))
  doc.text(bv.agentName || '', m + 4, y + 7)
  if (bv.brokerage) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...h(PDF_COLORS.textMid))
    doc.text(bv.brokerage, m + 4, y + 12.5)
  }
  if (bv.phone) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...h(PDF_COLORS.brand))
    doc.text(bv.phone, W - m - 4, y + 7, { align: 'right' })
  }
  return y + 21
}

export function pdfSectionHeader(doc: jsPDF, label: string, y: number): number {
  const W = doc.internal.pageSize.getWidth()
  const m = PDF_SPACING.pageMargin
  const cW = W - m * 2
  doc.setFillColor(...h(PDF_COLORS.lightGray))
  doc.roundedRect(m, y, cW, 10, 1.5, 1.5, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...h(PDF_COLORS.brand))
  doc.text(label.toUpperCase(), m + 4, y + 6.5)
  return y + 14
}

export function pdfBodyText(doc: jsPDF, text: string, y: number): number {
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const m = PDF_SPACING.pageMargin
  const cW = W - m * 2
  const lh = PDF_SPACING.lineHeight
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...h(PDF_COLORS.text))
  const lines: string[] = doc.splitTextToSize(text, cW)
  lines.forEach((line: string) => {
    if (y > H - 18) { pdfFooter(doc); doc.addPage(); y = 20 }
    doc.text(line, m, y)
    y += lh
  })
  return y
}

export function pdfSections(
  doc: jsPDF,
  sections: Array<{ label: string; content: string }>,
  y: number,
  bv?: { agentName?: string; brokerage?: string; phone?: string } | null
): void {
  const H = doc.internal.pageSize.getHeight()
  if (bv?.agentName || bv?.phone) { y = pdfAgentBar(doc, bv, y); y += 4 }
  sections.forEach(({ label, content }) => {
    if (!content) return
    if (y > H - 40) { pdfFooter(doc); doc.addPage(); y = 20 }
    y = pdfSectionHeader(doc, label, y)
    y = pdfBodyText(doc, content, y)
    y += PDF_SPACING.paragraphGap
  })
  pdfFooter(doc)
}
