import jsPDF from 'jspdf'

export const PDF = {
  colors: {
    brand: '#1D9E75',
    brandDark: '#085041',
    headerBg: '#ffffff',
    pageBg: '#ffffff',
    text: '#1a1a2e',
    textMid: '#4a5568',
    textLight: '#718096',
    sectionBg: '#f8fafb',
    borderLight: '#e2e8f0',
    white: '#ffffff',
    gold: '#d4af37',
  },
  fonts: {
    titleSize: 24,
    subtitleSize: 14,
    sectionHeaderSize: 11,
    bodySize: 10,
    captionSize: 8,
    footerSize: 7,
  },
  spacing: {
    margin: 20,
    sectionGap: 16,
    lineHeight: 5.5,
    paragraphGap: 10,
  },
}

// Backward-compat aliases used by dashboard
export const PDF_COLORS = {
  brand: PDF.colors.brand,
  brandDark: PDF.colors.brandDark,
  dark: '#0d1117',
  text: PDF.colors.text,
  textMid: PDF.colors.textMid,
  textLight: PDF.colors.textLight,
  white: PDF.colors.white,
  lightGray: PDF.colors.sectionBg,
  border: PDF.colors.borderLight,
  gold: PDF.colors.gold,
}

export const PDF_FONTS = {
  title: { size: 22, weight: 'bold' },
  sectionHeader: { size: 13, weight: 'bold' },
  subheading: { size: 11, weight: 'bold' },
  body: { size: 10, weight: 'normal' },
  caption: { size: 9, weight: 'normal' },
  footer: { size: 7, weight: 'normal' },
}

export const PDF_SPACING = {
  pageMargin: PDF.spacing.margin,
  sectionGap: PDF.spacing.sectionGap,
  lineHeight: PDF.spacing.lineHeight,
  paragraphGap: PDF.spacing.paragraphGap,
}

function h(color: string): [number, number, number] {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(color)!
  return [parseInt(r[1], 16), parseInt(r[2], 16), parseInt(r[3], 16)]
}

export function cleanPdfText(text: string): string {
  return text
    .replace(/\[([^\]]+)\]/g, '')
    .replace(/---+/g, '')
    .replace(/\*\*/g, '')
    .replace(/[\u{1F000}-\u{1FFFF}]|[\u{2600}-\u{27BF}]|[︀-﻿]/gu, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

export function pdfHeader(doc: jsPDF, docType: string, rightLabel: string): number {
  const W = doc.internal.pageSize.getWidth()
  const m = PDF.spacing.margin

  // White header background
  doc.setFillColor(...h(PDF.colors.white))
  doc.rect(0, 0, W, 40, 'F')

  // Left green vertical accent bar
  doc.setFillColor(...h(PDF.colors.brand))
  doc.rect(0, 7, 3, 24, 'F')

  // Brand name — "Listing" dark + "Whisperer" green
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...h(PDF.colors.text))
  doc.text('Listing', m, 22)
  doc.setTextColor(...h(PDF.colors.brand))
  doc.text('Whisperer', m + doc.getTextWidth('Listing') + 1.5, 22)

  // Center: document type
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...h(PDF.colors.brand))
  doc.text(docType.toUpperCase(), W / 2, 22, { align: 'center' })

  // Right: property/contact label
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...h(PDF.colors.textMid))
  if (rightLabel) doc.text(rightLabel.slice(0, 55), W - m, 17, { align: 'right' })

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
  doc.setFontSize(7.5)
  doc.setTextColor(...h(PDF.colors.textLight))
  doc.text(dateStr, W - m, 25, { align: 'right' })

  // Bottom border line
  doc.setDrawColor(...h(PDF.colors.borderLight))
  doc.setLineWidth(0.3)
  doc.line(0, 40, W, 40)

  return 50
}

export function pdfFooter(
  doc: jsPDF,
  bv?: { agentName?: string; brokerage?: string } | null
): void {
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const m = PDF.spacing.margin
  const pageNum = (doc.internal as any).getCurrentPageInfo?.()?.pageNumber ?? 1

  // White footer background
  doc.setFillColor(...h(PDF.colors.white))
  doc.rect(0, H - 12, W, 12, 'F')

  // Top border
  doc.setDrawColor(...h(PDF.colors.borderLight))
  doc.setLineWidth(0.3)
  doc.line(0, H - 12, W, H - 12)

  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...h(PDF.colors.textLight))

  // Left: agent info
  if (bv?.agentName) {
    const agentLine = bv.agentName + (bv.brokerage ? ' · ' + bv.brokerage : '')
    doc.text(agentLine.slice(0, 50), m, H - 4.5)
  }

  // Center: branding
  doc.text('Generated by ListingWhisperer.com', W / 2, H - 4.5, { align: 'center' })

  // Right: page number
  doc.text(`Page ${pageNum}`, W - m, H - 4.5, { align: 'right' })
}

export function pdfAgentBar(
  doc: jsPDF,
  bv: { agentName?: string; brokerage?: string; phone?: string } | null | undefined,
  y: number
): number {
  if (!bv?.agentName && !bv?.phone) return y
  const W = doc.internal.pageSize.getWidth()
  const m = PDF.spacing.margin
  const cW = W - m * 2

  doc.setFillColor(...h(PDF.colors.sectionBg))
  doc.roundedRect(m, y, cW, 14, 2, 2, 'F')
  doc.setDrawColor(...h(PDF.colors.borderLight))
  doc.setLineWidth(0.3)
  doc.roundedRect(m, y, cW, 14, 2, 2, 'S')

  // Left accent bar inside agent card
  doc.setFillColor(...h(PDF.colors.brand))
  doc.rect(m, y, 3, 14, 'F')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...h(PDF.colors.text))
  doc.text(bv.agentName || '', m + 7, y + 6)

  if (bv.brokerage) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...h(PDF.colors.textMid))
    doc.text(bv.brokerage, m + 7, y + 11.5)
  }

  if (bv.phone) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...h(PDF.colors.brand))
    doc.text(bv.phone, W - m - 4, y + 6, { align: 'right' })
  }

  return y + 20
}

export function pdfSectionHeader(doc: jsPDF, label: string, y: number): number {
  const W = doc.internal.pageSize.getWidth()
  const m = PDF.spacing.margin
  const cW = W - m * 2

  // Light gray background
  doc.setFillColor(...h(PDF.colors.sectionBg))
  doc.roundedRect(m, y, cW, 9, 1, 1, 'F')

  // Left green accent bar
  doc.setFillColor(...h(PDF.colors.brand))
  doc.rect(m, y, 3, 9, 'F')

  // Label in brand green, title-cased
  const titleCase = label.replace(/\b\w/g, c => c.toUpperCase())
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...h(PDF.colors.brand))
  doc.text(titleCase, m + 7, y + 6.2)

  return y + 13
}

export function pdfBodyText(
  doc: jsPDF,
  text: string,
  y: number,
  bv?: { agentName?: string; brokerage?: string } | null
): number {
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const m = PDF.spacing.margin
  const cW = W - m * 2
  const lh = PDF.spacing.lineHeight

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...h(PDF.colors.text))

  const cleaned = cleanPdfText(text)
  const lines: string[] = doc.splitTextToSize(cleaned, cW)

  lines.forEach((line: string) => {
    if (y > H - 18) {
      pdfFooter(doc, bv)
      doc.addPage()
      y = 20
    }
    doc.text(line, m, y)
    y += lh
  })

  return y
}

export function pdfStatCards(
  doc: jsPDF,
  stats: Array<{ label: string; value: string }>,
  y: number
): number {
  const W = doc.internal.pageSize.getWidth()
  const m = PDF.spacing.margin
  const gap = 6
  const cW = W - m * 2
  const cardW = (cW - gap * (stats.length - 1)) / stats.length

  stats.forEach((stat, i) => {
    const x = m + i * (cardW + gap)

    // Card background
    doc.setFillColor(...h(PDF.colors.sectionBg))
    doc.roundedRect(x, y, cardW, 24, 2, 2, 'F')

    // Top accent bar
    doc.setFillColor(...h(PDF.colors.brand))
    doc.rect(x, y, cardW, 2, 'F')

    // Value — large, brand green
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...h(PDF.colors.brand))
    const valLines = doc.splitTextToSize(stat.value || '—', cardW - 4)
    doc.text(valLines[0], x + cardW / 2, y + 14, { align: 'center' })

    // Label — small, muted
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...h(PDF.colors.textLight))
    doc.text(stat.label, x + cardW / 2, y + 21, { align: 'center' })
  })

  return y + 30
}

export function pdfSections(
  doc: jsPDF,
  sections: Array<{ label: string; content: string }>,
  y: number,
  bv?: { agentName?: string; brokerage?: string; phone?: string } | null
): void {
  const H = doc.internal.pageSize.getHeight()
  if (bv?.agentName || bv?.phone) { y = pdfAgentBar(doc, bv, y); y += 4 }
  sections.forEach(({ label, content }) => {
    if (!content?.trim()) return
    if (y > H - 40) { pdfFooter(doc, bv); doc.addPage(); y = 20 }
    y = pdfSectionHeader(doc, label, y)
    y = pdfBodyText(doc, content, y, bv)
    y += PDF.spacing.paragraphGap
  })
  pdfFooter(doc, bv)
}
